name: Azure WebApp Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'  # Change this to your .NET version

      - name: Restore dependencies
        run: dotnet restore ./MyWebApp/MyWebApp.csproj  # Specify path to your .csproj file

      - name: Build the application
        run: dotnet build ./MyWebApp/MyWebApp.csproj --configuration Release  # Specify path to your .csproj file

      - name: Publish the application
        run: dotnet publish ./MyWebApp/MyWebApp.csproj --configuration Release --output ./publish  # Specify path to your .csproj file

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'your-app-name'  # Replace with your Azure App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './publish'
